M48
; DRILL file {KiCad 7.0.8} date Wed Nov 15 18:30:56 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-15T18:30:56+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0930
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1100
%
G90
G05
T1
X5.2217Y-2.242
X5.5367Y-2.242
T2
X2.5796Y-3.6119
X2.5796Y-4.2025
T3
X2.4221Y-3.6119
X2.4221Y-4.2025
T0
M30
